-- DB dump generated by DbDumpTool
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `appointments`
-- ----------------------------
DROP TABLE IF EXISTS `appointments`;
CREATE TABLE `appointments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `appointment_time` datetime(6) DEFAULT NULL,
  `duration_minutes` int DEFAULT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `doctor_id` bigint DEFAULT NULL,
  `patient_id` bigint DEFAULT NULL,
  `check_in_time` datetime(6) DEFAULT NULL,
  `consultation_end_time` datetime(6) DEFAULT NULL,
  `consultation_start_time` datetime(6) DEFAULT NULL,
  `follow_up_date` date DEFAULT NULL,
  `queue_number` int DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'PENDING',
  PRIMARY KEY (`id`),
  KEY `FK6u6s6egu60m2cbdjno44jbipa` (`doctor_id`),
  KEY `FKopb2h9yhin1rb4dqote8bws6w` (`patient_id`),
  CONSTRAINT `FK6u6s6egu60m2cbdjno44jbipa` FOREIGN KEY (`doctor_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FKopb2h9yhin1rb4dqote8bws6w` FOREIGN KEY (`patient_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `appointments` (`id`,`appointment_time`,`duration_minutes`,`reason`,`doctor_id`,`patient_id`,`check_in_time`,`consultation_end_time`,`consultation_start_time`,`follow_up_date`,`queue_number`,`status`) VALUES (1,'2026-04-25 10:00:00',30,'Test initial booking',3,4,NULL,NULL,NULL,NULL,1,'CANCELLED');
INSERT INTO `appointments` (`id`,`appointment_time`,`duration_minutes`,`reason`,`doctor_id`,`patient_id`,`check_in_time`,`consultation_end_time`,`consultation_start_time`,`follow_up_date`,`queue_number`,`status`) VALUES (2,'2026-04-26 11:00:00',30,'Test rescheduled booking',3,4,NULL,NULL,NULL,NULL,1,'PENDING');
INSERT INTO `appointments` (`id`,`appointment_time`,`duration_minutes`,`reason`,`doctor_id`,`patient_id`,`check_in_time`,`consultation_end_time`,`consultation_start_time`,`follow_up_date`,`queue_number`,`status`) VALUES (3,'2026-04-25 10:00:00',30,'Test initial booking',3,4,NULL,NULL,NULL,NULL,2,'CANCELLED');
INSERT INTO `appointments` (`id`,`appointment_time`,`duration_minutes`,`reason`,`doctor_id`,`patient_id`,`check_in_time`,`consultation_end_time`,`consultation_start_time`,`follow_up_date`,`queue_number`,`status`) VALUES (4,'2026-04-26 11:00:00',30,'Test rescheduled booking',3,4,NULL,NULL,NULL,NULL,2,'PENDING');
INSERT INTO `appointments` (`id`,`appointment_time`,`duration_minutes`,`reason`,`doctor_id`,`patient_id`,`check_in_time`,`consultation_end_time`,`consultation_start_time`,`follow_up_date`,`queue_number`,`status`) VALUES (5,'2026-04-23 14:49:00',30,'check up',3,4,NULL,NULL,NULL,NULL,1,'PENDING');

-- ----------------------------
-- Table structure for `availability_slots`
-- ----------------------------
DROP TABLE IF EXISTS `availability_slots`;
CREATE TABLE `availability_slots` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `active` bit(1) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `end_date_time` datetime(6) DEFAULT NULL,
  `start_date_time` datetime(6) DEFAULT NULL,
  `doctor_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK5v4ab9hx2i24g3q6bw7q1494f` (`doctor_id`),
  CONSTRAINT `FK5v4ab9hx2i24g3q6bw7q1494f` FOREIGN KEY (`doctor_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- ----------------------------
-- Table structure for `billings`
-- ----------------------------
DROP TABLE IF EXISTS `billings`;
CREATE TABLE `billings` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `appointment_id` bigint DEFAULT NULL,
  `consultation_fee` double DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `medicine_cost` double DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `total_amount` double DEFAULT NULL,
  `payment_status` enum('PAID','UNPAID') DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- ----------------------------
-- Table structure for `departments`
-- ----------------------------
DROP TABLE IF EXISTS `departments`;
CREATE TABLE `departments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `departments` (`id`,`description`,`name`,`phone`) VALUES (1,'Heart and cardiovascular disease treatment','Cardiology','555-2001');
INSERT INTO `departments` (`id`,`description`,`name`,`phone`) VALUES (2,'Child health and development specialists','Pediatrics','555-2002');
INSERT INTO `departments` (`id`,`description`,`name`,`phone`) VALUES (3,'Bone and joint disorder specialists','Orthopedics','555-2003');
INSERT INTO `departments` (`id`,`description`,`name`,`phone`) VALUES (4,'Skin condition and disorder treatment','Dermatology','555-2004');
INSERT INTO `departments` (`id`,`description`,`name`,`phone`) VALUES (5,'Surgical procedures and interventions','General Surgery','555-2005');

-- ----------------------------
-- Table structure for `doctors`
-- ----------------------------
DROP TABLE IF EXISTS `doctors`;
CREATE TABLE `doctors` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `bio` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `specialization` varchar(255) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `department_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKt1f6cueqyjwx5ghew9ar1exe3` (`user_id`),
  KEY `FKl2mro81neln9topymd898urh1` (`department_id`),
  CONSTRAINT `FKe9pf5qtxxkdyrwibaevo9frtk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FKl2mro81neln9topymd898urh1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `doctors` (`id`,`bio`,`phone`,`specialization`,`user_id`,`department_id`) VALUES (1,'Experienced cardiologist with 10+ years of practice','+1-555-0100','Cardiology',3,NULL);
INSERT INTO `doctors` (`id`,`bio`,`phone`,`specialization`,`user_id`,`department_id`) VALUES (2,'Experienced interventional cardiologist with 15 years of practice','555-0101','Interventional Cardiology',6,1);
INSERT INTO `doctors` (`id`,`bio`,`phone`,`specialization`,`user_id`,`department_id`) VALUES (3,'Specialist in congenital heart diseases','555-0102','Pediatric Cardiology',7,1);
INSERT INTO `doctors` (`id`,`bio`,`phone`,`specialization`,`user_id`,`department_id`) VALUES (4,'Expert in child health and development','555-0103','General Pediatrics',8,2);
INSERT INTO `doctors` (`id`,`bio`,`phone`,`specialization`,`user_id`,`department_id`) VALUES (5,'Specializes in newborn care','555-0104','Neonatology',9,2);
INSERT INTO `doctors` (`id`,`bio`,`phone`,`specialization`,`user_id`,`department_id`) VALUES (6,'Expert in bone and joint disorders','555-0105','Orthopedic Surgery',10,3);
INSERT INTO `doctors` (`id`,`bio`,`phone`,`specialization`,`user_id`,`department_id`) VALUES (7,'Specializes in sports-related injuries','555-0106','Sports Medicine',11,3);
INSERT INTO `doctors` (`id`,`bio`,`phone`,`specialization`,`user_id`,`department_id`) VALUES (8,'Treats skin conditions and disorders','555-0107','Medical Dermatology',12,4);
INSERT INTO `doctors` (`id`,`bio`,`phone`,`specialization`,`user_id`,`department_id`) VALUES (9,'Specialist in aesthetic skin procedures','555-0108','Cosmetic Dermatology',13,4);
INSERT INTO `doctors` (`id`,`bio`,`phone`,`specialization`,`user_id`,`department_id`) VALUES (10,'Experienced surgical specialist','555-0109','General Surgery',14,5);
INSERT INTO `doctors` (`id`,`bio`,`phone`,`specialization`,`user_id`,`department_id`) VALUES (11,'Expert in minimally invasive procedures','555-0110','Laparoscopic Surgery',15,5);

-- ----------------------------
-- Table structure for `medical_records`
-- ----------------------------
DROP TABLE IF EXISTS `medical_records`;
CREATE TABLE `medical_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `diagnosis` varchar(255) DEFAULT NULL,
  `notes` longtext,
  `treatment` varchar(255) DEFAULT NULL,
  `visit_date` datetime(6) DEFAULT NULL,
  `doctor_id` bigint DEFAULT NULL,
  `patient_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKkew56covm00kqia866qlo6n4` (`doctor_id`),
  KEY `FKe3g9v0pbec2843wd1rxeb0is3` (`patient_id`),
  CONSTRAINT `FKe3g9v0pbec2843wd1rxeb0is3` FOREIGN KEY (`patient_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FKkew56covm00kqia866qlo6n4` FOREIGN KEY (`doctor_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- ----------------------------
-- Table structure for `medicines`
-- ----------------------------
DROP TABLE IF EXISTS `medicines`;
CREATE TABLE `medicines` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` longtext,
  `name` varchar(255) DEFAULT NULL,
  `price` double DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `medicines` (`id`,`description`,`name`,`price`,`quantity`) VALUES (1,'','sgsf4',23.0,55);

-- ----------------------------
-- Table structure for `patients`
-- ----------------------------
DROP TABLE IF EXISTS `patients`;
CREATE TABLE `patients` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `address` varchar(255) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK9tbsl3fmey0eofbm2xj69v4qs` (`user_id`),
  CONSTRAINT `FKuwca24wcd1tg6pjex8lmc0y7` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `patients` (`id`,`address`,`dob`,`phone`,`user_id`) VALUES (1,'123 Main St, Springfield',NULL,'+1-555-0200',4);

-- ----------------------------
-- Table structure for `pharmacy_records`
-- ----------------------------
DROP TABLE IF EXISTS `pharmacy_records`;
CREATE TABLE `pharmacy_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `dispensed_at` datetime(6) DEFAULT NULL,
  `medicine_id` bigint DEFAULT NULL,
  `prescription_id` bigint DEFAULT NULL,
  `quantity_dispensed` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- ----------------------------
-- Table structure for `prescription_medicines`
-- ----------------------------
DROP TABLE IF EXISTS `prescription_medicines`;
CREATE TABLE `prescription_medicines` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `dosage` varchar(255) DEFAULT NULL,
  `duration_days` int DEFAULT NULL,
  `instructions` longtext,
  `medicine_id` bigint DEFAULT NULL,
  `prescription_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKkljsa0768eycowt9le7nb215q` (`medicine_id`),
  KEY `FK14vcxytfp7rr81y9fdhl37bbw` (`prescription_id`),
  CONSTRAINT `FK14vcxytfp7rr81y9fdhl37bbw` FOREIGN KEY (`prescription_id`) REFERENCES `prescriptions` (`id`),
  CONSTRAINT `FKkljsa0768eycowt9le7nb215q` FOREIGN KEY (`medicine_id`) REFERENCES `medicines` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- ----------------------------
-- Table structure for `prescriptions`
-- ----------------------------
DROP TABLE IF EXISTS `prescriptions`;
CREATE TABLE `prescriptions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `medications` longtext,
  `notes` longtext,
  `appointment_id` bigint DEFAULT NULL,
  `doctor_id` bigint DEFAULT NULL,
  `patient_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKr0yn695qg51gn0iskc8p0h2ii` (`appointment_id`),
  KEY `FK2hdpvkpjjx3plf21194oxjskt` (`doctor_id`),
  KEY `FK7sia9wnwh9j5hwrta9k8q0rbq` (`patient_id`),
  CONSTRAINT `FK2hdpvkpjjx3plf21194oxjskt` FOREIGN KEY (`doctor_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FK7sia9wnwh9j5hwrta9k8q0rbq` FOREIGN KEY (`patient_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FKe2fpvlkkcgcd40k4ufyyju2al` FOREIGN KEY (`appointment_id`) REFERENCES `appointments` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `prescriptions` (`id`,`created_at`,`medications`,`notes`,`appointment_id`,`doctor_id`,`patient_id`) VALUES (1,'2026-04-23 14:51:28.872920','55f
hh
jj
','',5,3,4);

-- ----------------------------
-- Table structure for `users`
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `role` enum('ADMIN','DOCTOR','PATIENT') DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK6dotkott2kjsp8vw4d0m25fb7` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (1,'admin@ehealth.com','Admin User','$2a$10$LSf7yzii.YERiCQ638Rz5unpFSDum.UZNf2a6UcYi8YDb4Zl6uQz2','ADMIN');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (3,'doctor@ehealth.com','Dr. John Smith','$2a$10$4oyWC03e.ggIy7T7n0739emOF19m7aGhPWc1idkFOuW6FEgcgrQ1W','DOCTOR');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (4,'patient@ehealth.com','Jane Doe','$2a$10$yxAjtAuWTVmceRe2hx6hPeH5hbA17FuzEc0dTw0.hAkoI4amxDDgG','PATIENT');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (5,'ram@gmail.com','ram','$2a$10$Kf/9HsUHI31dER6R8ZQ.S.fhnr4IKcqQzcs2srRzP5ZrHhYjNbHuC','PATIENT');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (6,'john.smith@hospital.com','Dr. John Smith','$2a$10$slYQmyNdGzin7olVN3p5Be7DWRvEJiHf7/N8qF8nK2H5E8F9m5W1K','DOCTOR');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (7,'sarah.johnson@hospital.com','Dr. Sarah Johnson','$2a$10$slYQmyNdGzin7olVN3p5Be7DWRvEJiHf7/N8qF8nK2H5E8F9m5W1K','DOCTOR');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (8,'michael.chen@hospital.com','Dr. Michael Chen','$2a$10$slYQmyNdGzin7olVN3p5Be7DWRvEJiHf7/N8qF8nK2H5E8F9m5W1K','DOCTOR');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (9,'emma.davis@hospital.com','Dr. Emma Davis','$2a$10$slYQmyNdGzin7olVN3p5Be7DWRvEJiHf7/N8qF8nK2H5E8F9m5W1K','DOCTOR');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (10,'robert.wilson@hospital.com','Dr. Robert Wilson','$2a$10$slYQmyNdGzin7olVN3p5Be7DWRvEJiHf7/N8qF8nK2H5E8F9m5W1K','DOCTOR');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (11,'lisa.anderson@hospital.com','Dr. Lisa Anderson','$2a$10$slYQmyNdGzin7olVN3p5Be7DWRvEJiHf7/N8qF8nK2H5E8F9m5W1K','DOCTOR');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (12,'james.martinez@hospital.com','Dr. James Martinez','$2a$10$slYQmyNdGzin7olVN3p5Be7DWRvEJiHf7/N8qF8nK2H5E8F9m5W1K','DOCTOR');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (13,'patricia.taylor@hospital.com','Dr. Patricia Taylor','$2a$10$slYQmyNdGzin7olVN3p5Be7DWRvEJiHf7/N8qF8nK2H5E8F9m5W1K','DOCTOR');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (14,'david.lee@hospital.com','Dr. David Lee','$2a$10$slYQmyNdGzin7olVN3p5Be7DWRvEJiHf7/N8qF8nK2H5E8F9m5W1K','DOCTOR');
INSERT INTO `users` (`id`,`email`,`name`,`password`,`role`) VALUES (15,'maria.garcia@hospital.com','Dr. Maria Garcia','$2a$10$slYQmyNdGzin7olVN3p5Be7DWRvEJiHf7/N8qF8nK2H5E8F9m5W1K','DOCTOR');

SET FOREIGN_KEY_CHECKS=1;
