package hospital.tools;

import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class DbDumpTool {
    public static void main(String[] args) throws Exception {
        if (args.length < 4) {
            System.err.println("Usage: DbDumpTool <jdbcUrl> <user> <password> <outputFile>");
            System.exit(2);
        }
        String url = args[0];
        String user = args[1];
        String password = args[2];
        String outputPath = args[3];

        try (Connection conn = DriverManager.getConnection(url, user, password);
             PrintWriter out = new PrintWriter(new OutputStreamWriter(new FileOutputStream(outputPath), "UTF-8"))) {

            String dbName = conn.getCatalog();
            if (dbName == null || dbName.isEmpty()) {
                dbName = extractDbFromUrl(url);
            }

            out.println("-- DB dump generated by DbDumpTool");
            out.println("SET FOREIGN_KEY_CHECKS=0;");

            PreparedStatement psTables = conn.prepareStatement(
                    "SELECT TABLE_NAME FROM information_schema.tables WHERE TABLE_SCHEMA = ? AND TABLE_TYPE='BASE TABLE' ORDER BY TABLE_NAME");
            psTables.setString(1, dbName);
            ResultSet rsTables = psTables.executeQuery();
            List<String> tables = new ArrayList<>();
            while (rsTables.next()) {
                tables.add(rsTables.getString(1));
            }
            rsTables.close();
            psTables.close();

            for (String table : tables) {
                out.println();
                try (PreparedStatement psCreate = conn.prepareStatement("SHOW CREATE TABLE `" + table + "`");
                     ResultSet rsCreate = psCreate.executeQuery()) {
                    if (rsCreate.next()) {
                        String create = rsCreate.getString(2);
                        out.println("-- ----------------------------");
                        out.println("-- Table structure for `" + table + "`");
                        out.println("-- ----------------------------");
                        out.println("DROP TABLE IF EXISTS `" + table + "`;");
                        out.println(create + ";");
                        out.println();
                    }
                }

                try (Statement st = conn.createStatement();
                     ResultSet rs = st.executeQuery("SELECT * FROM `" + table + "`")) {
                    ResultSetMetaData rsmd = rs.getMetaData();
                    int colCount = rsmd.getColumnCount();
                    while (rs.next()) {
                        StringBuilder sb = new StringBuilder();
                        sb.append("INSERT INTO `").append(table).append("` (");
                        for (int i = 1; i <= colCount; i++) {
                            if (i > 1) sb.append(",");
                            sb.append("`").append(rsmd.getColumnName(i)).append("`");
                        }
                        sb.append(") VALUES (");
                        for (int i = 1; i <= colCount; i++) {
                            if (i > 1) sb.append(",");
                            Object val = rs.getObject(i);
                            if (val == null) {
                                sb.append("NULL");
                            } else if (val instanceof Number) {
                                sb.append(val.toString());
                            } else {
                                String s = rs.getString(i);
                                if (s == null) {
                                    sb.append("NULL");
                                } else {
                                    s = s.replace("\\", "\\\\").replace("'", "\\'");
                                    sb.append("'").append(s).append("'");
                                }
                            }
                        }
                        sb.append(");");
                        out.println(sb.toString());
                    }
                }
            }

            out.println();
            out.println("SET FOREIGN_KEY_CHECKS=1;");
            System.out.println("Dump written to " + outputPath);
        }
    }

    private static String extractDbFromUrl(String url) {
        int idx = url.indexOf('?');
        String base = (idx >= 0) ? url.substring(0, idx) : url;
        int lastSlash = base.lastIndexOf('/');
        if (lastSlash >= 0) {
            return base.substring(lastSlash + 1);
        }
        return "";
    }
}
